# A generic, single database configuration.

[alembic]
# path to migration script directory
script_location = backend/migrations

# template used to generate migration file names
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters in slug
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a matching .py file to be run as revisions
# sourceless = false

# version location specification
version_locations = %(here)s/migrations/versions

sqlalchemy.url = postgresql+psycopg://postgres:postgres@localhost:5432/haziva

[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
